/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- `characters`.stats_from_dungeons definition
DROP TABLE IF EXISTS `stats_from_dungeons`;

CREATE TABLE `stats_from_dungeons` (
  `GUID` int(10) unsigned NOT NULL,
  `Strength` float NOT NULL DEFAULT '0',
  `Agility` float NOT NULL DEFAULT '0',
  `Stamina` float NOT NULL DEFAULT '0',
  `Intellect` float NOT NULL DEFAULT '0',
  `Spirit` float NOT NULL DEFAULT '0',
  `SpellPower` int(11) unsigned NOT NULL DEFAULT '0',
  `AttackPower` float NOT NULL DEFAULT '0',
  `RAttackPower` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;